# Generated by Django 5.1.4 on 2025-01-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0002_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
